# config.yaml

size: 800
inf_name: "swin_backbone-swin_tiny_patch4_window7_224_fpn-True_lora-False_bs-1_lr-0.00042085894570310326_accum-1_size-800-val_f1=0.97.ckpt"

model:
  nclasses: 2
  model_type: "swin" #swin, fasterrcnn, custom
  backbone_name: "swin_base_patch4_window7_224" #swin_base_patch4_window7_224, swin_tiny_patch4_window7_224
  fpn: false
  size: ${size}
  lora: false

# Training parameters
training:
  batch_size: 3
  epochs: 10
  learning_rate: 0.001
  accum: 4
  debug: false

paths:
  train: "data/train/"
  validation: "data/validation/"
  test: "data/test/"
  labels: "data/labels.json"
  checkpoints: "output/checkpoints/"
  output_images: "output/images/"
  model_path: "models/fasterrcnn"

train_transforms:
  - name: Resize
    height: ${size}
    width: ${size}
    p: 1.0

  - name: RandomBrightnessContrast
    brightness_limit: 0.1
    contrast_limit: 0.1

  - name: Rotate
    limit: 30
    p: 0.5

  - name: Affine
    translate_percent: 0.1
    scale: 1.0
    rotate: 0
    p: 0.5

  - name: Normalize
    mean: [0, 0, 0]
    std: [1, 1, 1]
    max_pixel_value: 255.0

  - name: ToTensorV2

test_transforms:
  - name: Resize
    height: ${size}
    width: ${size}
    p: 1.0

  - name: Normalize
    mean: [0, 0, 0]
    std: [1, 1, 1]
    max_pixel_value: 255.0

  - name: ToTensorV2
