# config.yaml

# Training parameters
training:
  batch_size: 2
  epochs: 30
  learning_rate: 1e-5 #cuidado con explosi√≥n de gradiente
  debug: false

paths:
  data: "data/dataset"
  checkpoints: "output/checkpoints"
  output_images: "output/images"
  model_path: "models/detr"

train_transforms:
  - name: RandomBrightnessContrast
    brightness_limit: 0.1
    contrast_limit: 0.1

  - name: Rotate
    limit: 30
    p: 0.5

  - name: Affine
    translate_percent: 0.1
    scale: 1.0
    rotate: 0
    p: 0.5

  - name: ToTensorV2

test_transforms:
  - name: ToTensorV2
